update function-print-italic-string
error of argument numbers added.

diff --git a/function-print-italic-string b/function-print-italic-string
--- a/function-print-italic-string
+++ b/function-print-italic-string
@@ -1,5 +1,9 @@
 #!/bin/bash
 
 function function_print_italic_string {
+    if [[ $# -ne 1 ]]; then
+        echo "ERROR: you should pass exactly 1 argument."
+        exit 1
+    fi
     echo -e "\e[3m$1\e[0m"
 }
