update function-print-bold-string
error of argument numbers added.

diff --git a/function-print-bold-string b/function-print-bold-string
--- a/function-print-bold-string
+++ b/function-print-bold-string
@@ -1,5 +1,9 @@
 #!/bin/bash
 
 function_print_bold_string () {
+    if [[ $# -ne 1 ]]; then
+        echo "ERROR: you should pass exactly 1 argument."
+        exit 1
+    fi
     tput bold; echo $1; tput sgr0
 }
