update function-get-directory-size
errors considered: counts of arguments and type of argument

diff --git a/function-get-directory-size b/function-get-directory-size
--- a/function-get-directory-size
+++ b/function-get-directory-size
@@ -1,6 +1,14 @@
 #!/bin/bash
 
 function_get_directory_size() {
+    if [[ $# -ne 1 ]]; then
+        echo "ERROR: more than 1 arguments."
+        exit 1
+    fi
+    if [[ ! -d $1 ]]; then
+        echo "ERROR: $1 is not a directory"
+        exit 1
+    fi
     size=$(du -s -h -m $1 2> /dev/null | cut -d "/" -f 1)
     size=$(echo $size | tr -d '*')
     echo "$size megabytes"
